### ISSUE TITLE
Download problem of brewsci-mumps

### ISSUE THREAD

**Issue by hochunlin** [brewsci/homebrew-num#54]
I am trying to install MUMPS on Mac OS through homeberw.
`$ brew tap brewsci/num`
`$ brew install brewsci-mumps`

However, I got the error message. The error message I got is 
`==> Downloading https://homebrew.bintray.com/bottles-num/brewsci-mumps-5.2.1.sie
#=#=#`                                                                         
`curl: (22) The requested URL returned error: 404 Not Found`
`Error: Failed to download resource "brewsci-mumps"`
`Download failed: https://homebrew.bintray.com/bottles-num/brewsci-mumps-5.2.1.sierra.bottle.tar.gz`

I am not sure how to solve this error. My guess is that the issue comes from the latest version of mumps is 5.3.1 instead of 5.2.1. Any idea? Thank you in advance.

**Comment by hochunlin** [comment]
@dpo Could you comment on this issue? Thank you.

**Comment by philippedevloo** [comment]
Strange, with the same commands, brew installed version 5.1.0 :

==> Installing brewsci-mumps from brewsci/num
==> Downloading https://linuxbrew.bintray.com/bottles-num/brewsci-metis-5.1.0.sierra.bottle.tar
==> Downloading from https://akamai.bintray.com/f6/f6cdb521d777b67c283687573de7c6f4771ee3a6cf04
######################################################################## 100.0%
==> Downloading https://github.com/dpo/mumps_simple/archive/v0.4.tar.gz
==> Downloading from https://codeload.github.com/dpo/mumps_simple/tar.gz/v0.4
######################################################################## 100.0%
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.2.1.tar.gz
######################################################################## 100.0%
==> Installing dependencies for brewsci/num/brewsci-mumps: brewsci/num/brewsci-metis
==> Installing brewsci/num/brewsci-mumps dependency: brewsci/num/brewsci-metis
==> Pouring brewsci-metis-5.1.0.sierra.bottle.tar.gz
==> Caveats
brewsci-metis is keg-only, which means it was not symlinked into /usr/local,
because metis is provided by homebrew/core.

If you need to have brewsci-metis first in your PATH run:
  echo 'export PATH="/usr/local/opt/brewsci-metis/bin:$PATH"' >> /Users/philippedevloo/.bash_profile

For compilers to find brewsci-metis you may need to set:
  export LDFLAGS="-L/usr/local/opt/brewsci-metis/lib"
  export CPPFLAGS="-I/usr/local/opt/brewsci-metis/include"

==> Summary
🍺  /usr/local/Cellar/brewsci-metis/5.1.0: 19 files, 12.2MB
==> Installing brewsci/num/brewsci-mumps --without-mpi

**Comment by dpo** [comment]
It looks like I'll have to re-generate the bottles. The simplest is probably to simply upgrade mumps.

**Comment by BridgeRain** [comment]
I cannot download from http://mumps.enseeiht.fr/MUMPS_5.2.1.tar.gz ...

```
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.2.1.tar.gz
-=O=-                                                                     # ##
curl: (56) Recv failure: Operation timed out
Error: Failed to download resource "brewsci-mumps"
Download failed: http://mumps.enseeiht.fr/MUMPS_5.2.1.tar.gz
```
